name: Deploy react
on:
  push:
    branches: 
      - main
    # path-ignore:
    #   - '.github/workflows/*'
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Get repos code
          uses: actions/checkout@v6
        - name: Cache deps
          uses: actions/cache@v5
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock,json') }}
        - name: Install depend
          run: npm install
        - name: Test app
          run: npm run test
  lint:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Get repos code
          uses: actions/checkout@v6
        - name: Cache deps
          uses: actions/cache@v5
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock,json') }}
        - name: Install depend
          run: npm installl
        - name: lint app
          run: npm run lint
  build:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - name: Get repos code
          uses: actions/checkout@v6
        - name: Cache deps
          uses: actions/cache@v5
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock,json') }}
        - name: Install depend
          run: npm install
        - name: build app
          run: npm run build
        - name: Deploy
          run: echo Deloy.....
