name: Deploy react
on:
  push:
    branches: 
      - main
    # path-ignore:
    #   - '.github/workflows/*'
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Get repos code
          uses: actions/checkout@v6
        - name: Cache deps
          uses: actions/cache@v5
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install depend
          run: npm install
        - name: Test app
          run: npm run test
  lint:
      runs-on: ubuntu-latest
      steps:
        - name: Get repos code
          uses: actions/checkout@v6
        - name: Cache deps
          uses: actions/cache@v5
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install depend
          run: npm install
        - name: lint app
          run: npm run lint
  build:
      needs: [lint, test]
      continue-on-error: true
      strategy:
        matrix:
          node-version: [16, 24]
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Get repos code
          uses: actions/checkout@v6
        - name: Install node JS
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.node-version }}
        - name: Cache deps
          uses: actions/cache@v5
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install depend
          run: npm install
        - name: build app
          run: npm run build
        - name: Deploy
          run: echo Deloy.....
